# alacritty.toml â€” Main configuration file
#
# This file is used to override default alacritty settings, define
# (or import) custom commands, or run any other startup tasks.
# See https://alacritty.org/#configuration
#
# Colors - Tokyo Night

[general]
ipc_socket = true

[font]
normal = { family = "Hack Nerd Font" }
size = 14

[window]
padding = { x = 10, y = 10 }

[colors.primary]
foreground = "#c0caf5"
background = "#1a1b26"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "#c0caf5"
background = "#283457"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
